// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZUjO3_Bz93572tQqFSN7td1pabLfN-iw',
    appId: '1:339336551842:web:79f1fee0c96914145f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    authDomain: 'anany-me.firebaseapp.com',
    storageBucket: 'anany-me.appspot.com',
    measurementId: 'G-3BPDEGB72J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDpzH2MUTMPlJEofF-x1P7PC-BDDUK6zo',
    appId: '1:339336551842:android:4945eb2b65cf46605f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    storageBucket: 'anany-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVKD-66zHFfII8az_LCruXcNwwSzmLjU',
    appId: '1:339336551842:ios:df122dd3b31035b75f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    storageBucket: 'anany-me.appspot.com',
    iosBundleId: 'com.anany.hr360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVKD-66zHFfII8az_LCruXcNwwSzmLjU',
    appId: '1:339336551842:ios:df122dd3b31035b75f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    storageBucket: 'anany-me.appspot.com',
    iosBundleId: 'com.anany.hr360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZUjO3_Bz93572tQqFSN7td1pabLfN-iw',
    appId: '1:339336551842:web:67413b11b87298535f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    authDomain: 'anany-me.firebaseapp.com',
    storageBucket: 'anany-me.appspot.com',
    measurementId: 'G-921YP2GYR9',
  );
}
